import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import syllabus from "../syllabus/Syllabus";

function AssymetricKeyAndDigitalSignatures() {
  const navigate = useNavigate();

  return (
    <div>
      <div className="note">
        <h1>Asymmetric-Key Cryptography and Digital Signatures</h1>
        <p>
          Blockchain technology utilizes a key concept from Computer science
          called Asymmetric-Key Cryptography also referred to as public/private
          key cryptography. Asymmetric-key cryptography uses a pair of keys:
          public and private keys which are mathematically related to each
          other. As the name suggests, the public key is known by everyone
          participating in the network but the private key is kept secret to
          only the owner of a wallet. How they are used is Blockchain
        </p>
        <p>-The Private key is used to sign a transaction </p>
        <p>-The Public key are used to verify signatures that was generated by the private key</p>
      </div>
      <div className="absolute">
        {syllabus.map((syllabusItem) => (
          <button onClick={() => navigate("/topic" + syllabusItem.key)}>
            {syllabusItem.title}
          </button>
        ))}
      </div>
    </div>
  );
}

export default AssymetricKeyAndDigitalSignatures;
